//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brief.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Brief.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;XML&gt;
        ///  &lt;brief&gt;
        ///    &lt;adviseur&gt;
        ///      &lt;relatienummer&gt;123&lt;/relatienummer&gt;
        ///      &lt;naam&gt;Andre&lt;/naam&gt;
        ///      &lt;kopiegeprint&gt;J&lt;/kopiegeprint&gt;
        ///      &lt;isincasserend&gt;J&lt;/isincasserend&gt;
        ///    &lt;/adviseur&gt;
        ///    &lt;contactpersoon&gt;
        ///      &lt;achternaam&gt;Wessel&lt;/achternaam&gt;
        ///      &lt;voorletters&gt;A.H.J.&lt;/voorletters&gt;
        ///      &lt;salesmanager&gt;
        ///        &lt;voorletters&gt;A.A.A.&lt;/voorletters&gt;
        ///        &lt;naam&gt;ddddd&lt;/naam&gt;
        ///      &lt;/salesmanager&gt;
        ///    &lt;/contactpersoon&gt;
        ///  &lt;/brief&gt;
        ///&lt;/XML&gt;.
        /// </summary>
        internal static string testadviseur {
            get {
                return ResourceManager.GetString("testadviseur", resourceCulture);
            }
        }
    }
}
